# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cream}
  s.version = "0.8.9.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2011-02-28}
  s.description = %q{An integrated Authentication, Authorization and Roles solution for your Rails 3 app with support for multiple ORMs}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    ".bundle/config",
    ".document",
    ".rspec",
    "Changelog.txt",
    "Design Ideas.textile",
    "Gemfile",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/views/cream/menu/_admin_login_items.html.erb",
    "app/views/cream/menu/_login_items.html.erb",
    "app/views/cream/menu/_registration_items.html.erb",
    "config/locales/cream.da.yml",
    "config/locales/cream.en.yml",
    "features/FEATURE_NOTES.txt",
    "features/permission/adds_permission.feature",
    "features/role_strategy/adds_role_strategy.feature",
    "features/role_strategy/clears_role_strategy.feature",
    "init.rb",
    "lib/cream.rb",
    "lib/cream/configure/after_init/role_config.rb",
    "lib/cream/configure/engine.rb",
    "lib/cream/configure/rails.rb",
    "lib/cream/controller/ability.rb",
    "lib/cream/controller/user_control.rb",
    "lib/cream/helper/host.rb",
    "lib/cream/helper/role.rb",
    "lib/cream/namespaces.rb",
    "lib/cream/rails/config.rb",
    "lib/cream/role.rb",
    "lib/cream/roles_config.rb",
    "lib/cream/view/host_area.rb",
    "lib/cream/view/role_area.rb",
    "lib/cream/view/user_action_menu.rb",
    "lib/generators/cancan/config/config_generator.rb",
    "lib/generators/cream/app/app_generator.rb",
    "lib/generators/cream/core_ext.rb",
    "lib/generators/cream/full_config/full_config_generator.rb",
    "lib/generators/cream/helpers/all.rb",
    "lib/generators/cream/helpers/args_helper.rb",
    "lib/generators/cream/helpers/execute_helper.rb",
    "lib/generators/cream/helpers/gemfile_helper.rb",
    "lib/generators/cream/helpers/orm_helper.rb",
    "lib/generators/cream/helpers/strategy_helper.rb",
    "lib/generators/cream/views/haml_util.rb",
    "lib/generators/cream/views/views_generator.rb",
    "lib/generators/devise/config/app_helper.rb",
    "lib/generators/devise/config/config_generator.rb",
    "lib/generators/devise/config/gem_config_helper.rb",
    "lib/generators/devise/customize/customize_generator.rb",
    "lib/generators/devise/customize/customize_messages.rb",
    "lib/generators/devise/customize/helpers/query_customizers.rb",
    "lib/generators/devise/customize/helpers/recover_login.rb",
    "lib/generators/devise/customize/helpers/username_helper.rb",
    "lib/generators/devise/users/helper.rb",
    "lib/generators/devise/users/routes_helper.rb",
    "lib/generators/devise/users/users_generator.rb",
    "lib/generators/permits/config/config_generator.rb",
    "lib/generators/roles/config/config_generator.rb",
    "log/development.log",
    "sandbox/any_user.rb",
    "sandbox/cream_refactor.rb",
    "sandbox/str_test.rb",
    "sandbox/test.rb",
    "spec/configure_helper.rb",
    "spec/cream/configure/rails_custom_roles_spec.rb",
    "spec/cream/configure/rails_role_spec.rb",
    "spec/cream/configure/rails_user_roles_spec.rb",
    "spec/cream/helper/host_spec.rb",
    "spec/cream/helper/role_spec.rb",
    "spec/cream/view/host_area_spec.rb",
    "spec/cream/view/role_area_spec.rb",
    "spec/generator_spec_helper.rb",
    "spec/generators/cancan/config/cancan_config_generator_spec.rb",
    "spec/generators/cream/app/app_generator_spec.rb",
    "spec/generators/cream/full_config/full_config_generator_spec.rb",
    "spec/generators/cream/views_generator_spec.rb",
    "spec/generators/devise/config/devise_config_generator_spec.rb",
    "spec/generators/devise/users/devise_users_generator_spec.rb",
    "spec/generators/permits/config/permits_config_generator_spec.rb",
    "spec/generators/roles/config/roles_config_generator_spec.rb",
    "spec/spec_helper.rb",
    "wiki/Cream-generators-overview.textile",
    "wiki/How to gollum wiki.txt"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/cream}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Integrates Devise, CanCan with permits and Roles generic for multiple ORMs}
  s.test_files = [
    "spec/configure_helper.rb",
    "spec/cream/configure/rails_custom_roles_spec.rb",
    "spec/cream/configure/rails_role_spec.rb",
    "spec/cream/configure/rails_user_roles_spec.rb",
    "spec/cream/helper/host_spec.rb",
    "spec/cream/helper/role_spec.rb",
    "spec/cream/view/host_area_spec.rb",
    "spec/cream/view/role_area_spec.rb",
    "spec/generator_spec_helper.rb",
    "spec/generators/cancan/config/cancan_config_generator_spec.rb",
    "spec/generators/cream/app/app_generator_spec.rb",
    "spec/generators/cream/full_config/full_config_generator_spec.rb",
    "spec/generators/cream/views_generator_spec.rb",
    "spec/generators/devise/config/devise_config_generator_spec.rb",
    "spec/generators/devise/users/devise_users_generator_spec.rb",
    "spec/generators/permits/config/permits_config_generator_spec.rb",
    "spec/generators/roles/config/roles_config_generator_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.4.1"])
      s.add_development_dependency(%q<devise-spec>, [">= 0.1.3"])
      s.add_development_dependency(%q<roles-spec>, [">= 0.1.3"])
      s.add_runtime_dependency(%q<require_all>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<colorize>, [">= 0.5.8"])
      s.add_runtime_dependency(%q<cancan-rest-links>, [">= 0.2.2"])
      s.add_runtime_dependency(%q<devise>, [">= 1.1.5"])
      s.add_runtime_dependency(%q<cancan>, [">= 1.4.1"])
      s.add_runtime_dependency(%q<rails>, [">= 3.0.1"])
      s.add_runtime_dependency(%q<r3_plugin_toolbox>, [">= 0.4.1"])
      s.add_runtime_dependency(%q<sugar-high>, [">= 0.3.7"])
    else
      s.add_dependency(%q<rspec>, [">= 2.4.1"])
      s.add_dependency(%q<devise-spec>, [">= 0.1.3"])
      s.add_dependency(%q<roles-spec>, [">= 0.1.3"])
      s.add_dependency(%q<require_all>, ["~> 1.2.0"])
      s.add_dependency(%q<colorize>, [">= 0.5.8"])
      s.add_dependency(%q<cancan-rest-links>, [">= 0.2.2"])
      s.add_dependency(%q<devise>, [">= 1.1.5"])
      s.add_dependency(%q<cancan>, [">= 1.4.1"])
      s.add_dependency(%q<rails>, [">= 3.0.1"])
      s.add_dependency(%q<r3_plugin_toolbox>, [">= 0.4.1"])
      s.add_dependency(%q<sugar-high>, [">= 0.3.7"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.4.1"])
    s.add_dependency(%q<devise-spec>, [">= 0.1.3"])
    s.add_dependency(%q<roles-spec>, [">= 0.1.3"])
    s.add_dependency(%q<require_all>, ["~> 1.2.0"])
    s.add_dependency(%q<colorize>, [">= 0.5.8"])
    s.add_dependency(%q<cancan-rest-links>, [">= 0.2.2"])
    s.add_dependency(%q<devise>, [">= 1.1.5"])
    s.add_dependency(%q<cancan>, [">= 1.4.1"])
    s.add_dependency(%q<rails>, [">= 3.0.1"])
    s.add_dependency(%q<r3_plugin_toolbox>, [">= 0.4.1"])
    s.add_dependency(%q<sugar-high>, [">= 0.3.7"])
  end
end

